version: '3.8'

services:
  marklogic:
    image: store/marklogicdb/marklogic-server:10.0-8.1-centos-1.0.0-ea2
    domainname: .
    ports:
      - 5000:5000
      - 5432:5432
      - 7997-8013:7997-8013
      - 9002:9002
    container_name: "samlPoc.local"
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
      - TZ=Europe/Amsterdam
    volumes:
      - ./logs/samlpoc.local:/var/opt/MarkLogic/Logs
    networks:
      - external_net
      - internal_net

networks:
  external_net: {}
  internal_net:
    internal: true
